# Generated by Django 2.1.1 on 2018-10-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resultchart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=20, unique=True)),
                ('stime', models.DateTimeField(null=True)),
                ('etime', models.DateTimeField(null=True)),
                ('rtime', models.DateTimeField(null=True)),
                ('successrate', models.IntegerField()),
            ],
        ),
    ]
