# Generated by Django 2.1.1 on 2018-10-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_20181003_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultjs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsname', models.CharField(max_length=50)),
                ('errreason', models.CharField(max_length=100)),
            ],
        ),
    ]
