# Generated by Django 2.1.1 on 2018-10-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_auto_20181003_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultjs',
            name='stime',
            field=models.CharField(default=1000000000, max_length=20),
            preserve_default=False,
        ),
    ]
