# Generated by Django 2.1.1 on 2018-10-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_timejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='timejob',
            name='stat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
