# Generated by Django 2.1.3 on 2018-11-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_timejob_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultjs',
            name='errreason',
            field=models.CharField(max_length=3000),
        ),
    ]
