# Generated by Django 2.1.7 on 2019-02-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0011_userlogin_authorizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='password',
            new_name='passwd',
        ),
    ]
