# Generated by Django 2.1.7 on 2019-02-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0012_auto_20190218_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobileinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobname', models.CharField(max_length=30)),
                ('resolution_x', models.IntegerField()),
                ('resolution_y', models.IntegerField()),
                ('system_type', models.CharField(max_length=10)),
                ('system_numb', models.DecimalField(decimal_places=5, max_digits=10)),
                ('username', models.CharField(max_length=20)),
                ('frist_time', models.IntegerField()),
                ('last_time', models.IntegerField()),
            ],
        ),
    ]
