# Generated by Django 2.1.7 on 2019-02-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0013_mobileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileinfo',
            name='resolution_x',
        ),
        migrations.RemoveField(
            model_name='mobileinfo',
            name='resolution_y',
        ),
        migrations.AddField(
            model_name='mobileinfo',
            name='resolution',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
