# Generated by Django 2.1.7 on 2019-02-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0014_auto_20190222_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileinfo',
            name='mobstat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
