# Generated by Django 2.1.7 on 2019-02-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0015_mobileinfo_mobstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileinfo',
            name='frist_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mobileinfo',
            name='last_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mobileinfo',
            name='mobstat',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mobileinfo',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
