# Generated by Django 2.1.7 on 2019-02-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0016_auto_20190225_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='sys_dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dic_name', models.CharField(max_length=30)),
                ('deploy_name', models.CharField(max_length=30)),
                ('deploy_code', models.CharField(max_length=30)),
            ],
        ),
    ]
