# Generated by Django 2.1.7 on 2019-02-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0017_sys_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileinfo',
            name='mobmodel',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
