# Generated by Django 2.1.7 on 2019-02-26 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0018_mobileinfo_mobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileinfo',
            name='mobname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.sys_dict'),
        ),
        migrations.AlterField(
            model_name='sys_dict',
            name='deploy_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
