# Generated by Django 2.1.7 on 2019-02-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0019_auto_20190226_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sys_dict',
            name='deploy_code',
        ),
    ]
