# Generated by Django 2.1.7 on 2019-02-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0021_auto_20190227_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileinfo',
            name='create_time',
            field=models.IntegerField(default=1546272000),
        ),
    ]
