# Generated by Django 2.1.7 on 2019-03-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0022_mobileinfo_create_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resultchart',
        ),
        migrations.DeleteModel(
            name='resultjs',
        ),
        migrations.DeleteModel(
            name='timejob',
        ),
        migrations.AddField(
            model_name='mobileinfo',
            name='imgurl',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
