# Generated by Django 2.1.7 on 2019-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0023_auto_20190319_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileinfo',
            name='imgurl',
            field=models.CharField(default='http://julicool-img.oss-ap-southeast-1.aliyuncs.com/mob.jpg', max_length=500),
        ),
    ]
